ckanext/onboarding_baglan_adaskhan/logic/auth.py
import ckan.authz as authz
from ckanext.onboarding_baglan_adaskhan.authz import user_has_review_permission
from ckan.common import _
from ckan.logic.auth.update import package_update as core_package_update
import ckan.logic as logic


def package_update(context, data_dict):
    dataset_id = data_dict.get("id")
    skip_default = context.get("skip_default", False)

    dataset = logic.get_action("package_show")(context, {"id": dataset_id})
    current_review_status = dataset.get("review_status")

    if current_review_status == "pending" and not skip_default:
        return {"success": False, "msg": "Dataset is currently in review and cannot be updated."}

    if skip_default:
        return {"success": True}

    return core_package_update(context, data_dict)


def dataset_review(context, data_dict):
    user = context['user']
    user_id = authz.get_user_id_for_username(user, allow_none=True)

    if user and user_has_review_permission(user_id):
        return {'success': True}

    return {'success': False, 'msg': _('User %s not authorized to review datasets') % user}

ckanext/onboarding_baglan_adaskhan/views/admin.py
from flask import Blueprint
import ckan.lib.base as base
import ckan.model as model
import sqlalchemy

admin = Blueprint(u'onboarding_admin', __name__, url_prefix=u'/ckan-admin')


def _get_reviewers():
    q = model.Session.query(model.User).filter(
        model.User.plugin_extras.op("->>")("review_permission").cast(sqlalchemy.Boolean) == True,
        model.User.state == u'active')
    return q


def reviewers():
    data = dict(reviewers=[a.name for a in _get_reviewers()])
    return base.render(u'admin/reviewers.html', extra_vars=data)


admin.add_url_rule(
    u'/reviewers', view_func=reviewers, methods=['GET'], strict_slashes=False
)

ckanext/onboarding_baglan_adaskhan/views/dataset.py
import ckan.lib.base as base
import ckan.logic as logic
from ckan.common import _, current_user, request
from ckan.lib.helpers import helper_functions as h
from flask import Blueprint
import logging

log = logging.getLogger(__name__)

dataset = Blueprint("onboarding_dataset", __name__, url_prefix="/dataset")


def review():
    id = request.form.get("id")
    review_status = request.form.get("review_status")

    url = h.url_for("dataset.read", package_type="dataset", id=id)

    try:
        context = {
            "user": current_user.name,
            "auth_user_obj": current_user,
        }

        data_dict = {"id": id, "review_status": review_status}
        logic.get_action("dataset_review")(context, data_dict)
    except logic.NotAuthorized:
        return base.abort(403, _("Not authorized to review datasets"))
    except logic.NotFound:
        h.flash_error(_("Dataset not found"))
        return h.redirect_to("dataset.index")
    except logic.ValidationError as e:
        h.flash_error((e.message or e.error_summary or e.error_dict))
        return h.redirect_to(url)

    if review_status == "approved":
        h.flash_success(_("Successfully approved dataset"))
    else:
        h.flash_success(_("Succesfully rejected dataset"))
    return h.redirect_to(url)


dataset.add_url_rule(rule="/review", view_func=review, methods=["POST"])
dataset.add_url_rule(rule="/review", view_func=review, methods=["POST"])

ckanext/onboarding_baglan_adaskhan/views/home.py
from flask import Blueprint
import ckan.lib.base as base
import logging
from ckan.lib.dictization import table_dictize
from ckan.plugins.toolkit import get_action, request as toolkit_request
from ckanext.onboarding_baglan_adaskhan.model.dataset_review import DatasetReview
from ckan.common import g


log = logging.getLogger(__name__)

home = Blueprint("onboarding_home", __name__)


def about():
    log.debug("/about is being overriden")
    return base.render(u'home/about.html', extra_vars={})

def dataset_reviews():
    dataset_reviews_q = DatasetReview.list()
    dataset_reviews_list = dataset_reviews_q.all()

    log.debug(f"dataset_reviews_list {dataset_reviews_list}")

    user = g.user
    context = {"user": user}
    log.debug(f"context {context}")
    search_result = get_action("package_search")(context)
    log.debug(f"search_result {search_result}")
    allowed_dataset_ids = set(pkg["id"] for pkg in search_result["results"])
    log.debug(f"allowed_dataset_ids {allowed_dataset_ids}")

    visible_reviews = []
    for r in dataset_reviews_list:
        log.debug(f"package_id {r._mapping['package_id']}")

        if r._mapping["package_id"] in allowed_dataset_ids:
            visible_reviews.append(r)

    dataset_reviews_dict_list = [table_dictize(r, {}) for r in visible_reviews]

    return base.render(
        "dataset_reviews.html",
        extra_vars={"dataset_reviews": dataset_reviews_dict_list},
    )

home.add_url_rule("/about", view_func=about)
home.add_url_rule("/dataset_reviews", view_func=dataset_reviews)

ckanext/onboarding_baglan_adaskhan/views/user.py
import logging
from flask import Blueprint
from ckan.common import request, asbool, current_user, _
import ckan.lib.base as base
import ckan.logic as logic
from ckan.lib.helpers import helper_functions as h

log = logging.getLogger(__name__)
user = Blueprint(u'onboarding_user', __name__, url_prefix=u'/user')


def reviewers():
    username = request.form.get(u'username')
    status = asbool(request.form.get(u'status'))
    try:
        context = {
            u'user': current_user.name,
            u'auth_user_obj': current_user,
        }

        data_dict = {u'id': username, u'plugin_extras': { "review_permission": status }} # <===== ONLY THIS LINE CHANGED
        user = logic.get_action(u'user_patch')(context, data_dict)
    except logic.NotAuthorized:
        return base.abort(
            403,
            _(u'Not authorized to promote user to reviewer')
        )
    except logic.NotFound:
        h.flash_error(_(u'User not found'))
        return h.redirect_to(u'onboarding_admin.reviewers')
    except logic.ValidationError as e:
        h.flash_error((e.message or e.error_summary or e.error_dict))
        return h.redirect_to(u'onboarding_admin.reviewers')

    if status:
        h.flash_success(
            _(u'Promoted {} to reviewer'.format(user[u'display_name']))
        )
    else:
        h.flash_success(
            _(
                u'Revoked reviewer permission from {}'.format(
                    user[u'display_name']
                )
            )
        )
    return h.redirect_to(u'onboarding_admin.reviewers')


user.add_url_rule(rule=u'/reviewers', view_func=reviewers, methods=['POST'])

ckanext/onboarding_baglan_adaskhan/templates/base.html
{% ckan_extends %}


{%- block styles %}
    {{ super() }}
    {% asset 'onboarding_baglan_adaskhan/onboarding-css' %}
{% endblock %}


{% block scripts %}
    {% asset 'onboarding_baglan_adaskhan/onboarding-js' %}
    {{ super() }}
{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/dataset_reviews.html
{% extends "page.html" %}
{% block primary_content %}
   <table class="table">
      <tr>
        <th>Dataset</th>
        <th>Status</th>
        <th>Updated By</th>
        <th>Date</th>
      </tr>
      {% for dataset_review in dataset_reviews %}
        <tr>
            <td>
                <a href="{{ h.url_for('user.read', id=dataset_review.user_id) }}">
                    {{ dataset_review.username }}
                </a>
            </td>
            <td>{{ dataset_review.review_status }}</td>
            <td>
                <a href="{{ h.url_for('dataset.read', id=dataset_review.package_id) }}">
                    {{ dataset_review.dataset_title }}
                </a>
            </td>
            <td>{{ dataset_review.timestamp }}</td>
        </tr>
      {% endfor %}
    </table> 
{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/header.html
{% ckan_extends %}

{% block header_site_navigation_tabs %}
    {{ super() }}
    {{ h.build_nav_main(
        ('onboarding_home.dataset_reviews', _('My New Route'))
    )}}
{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/my_custom_template.html
{% extends "page.html" %}

{% block primary_content %}
    <div>
        <p>
            Hello World
        </p>
        <ul>
            <li>This is my custom route</li>
            <li>I can write HTML in the template that it's rendering</li>
            <li>This value is coming from the view function: {{ my_var }}</li>
        </ul>
    </div>
{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/package/edit_base.html
{% ckan_extends %}
{% block scripts %}
  {% asset 'onboarding_baglan_adaskhan/onboarding-js' %}
  {{ super() }}
  <script>
    $(function () {
      $('#field-private').attr('data-module', 'pending-review-confirm');
    });
  </script>
{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/package/read.html
{% ckan_extends %} 

{% block package_description %}
    {% set review_status_class = {
        "pending": "alert-warning",
        "approved": "alert-success",
        "rejected": "alert-danger"
    } %}
    {% set review_status = h.dataset_review_status(pkg.id) %}
    {% set current_user_is_reviewer = h.user_is_reviewer(g.user) %}
    {% snippet 'snippets/review_status_badge.html', review_status=review_status, review_status_class=review_status_class %}

    {{ super() }}
    <div class="p-2 {{ review_status_class.get(review_status) }}">
            {% if review_status == 'pending' %}
          This dataset is waiting for a review.
          {% if h.check_access('dataset_review', {'id': pkg.id}) %}
                <div>
                  <form method="POST" action="{{ url_for('onboarding_dataset.review')  }}" class="d-inline-block">
                      <input type="hidden" name="id" value="{{ pkg.id }}" />
                      <input type="hidden" name="review_status" value="approved" />
                      <button class="btn btn-success"
                              data-module="confirm-action"
                              data-module-content="{{ _('Are you sure you want to approve this dataset?') }}"
                              data-module-with-data=true
                              type="submit"
                        >
                            <i class="fa-solid fa-circle-plus"></i> Approve
                       </button>
                  </form>
                  <form method="POST" action="{{ url_for('onboarding_dataset.review')  }}" class="d-inline-block">
                       <input type="hidden" name="id" value="{{ pkg.id }}" />
                       <input type="hidden" name="review_status" value="rejected" />
                       <button class="btn btn-danger"
                               data-module="confirm-action"
                               data-module-content="{{ _('Are you sure you want to reject this dataset?') }}"
                               data-module-with-data=true
                               type="submit"
                       >
                           <i class="fa-solid fa-circle-minus"></i> Reject
                      </button>
                  </form>
                </div>
          {% endif %}
      {% endif %}
        {% if review_status == 'approved' %}
          This dataset has been reviewed and approved!
      {% endif %}

      {% if review_status == 'rejected' %} 
          This dataset has been reviewed and rejected!
      {% endif %}
    </div>
{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/scheming/display_snippets/dataset_review.html
{% set value = data[field.field_name] %}

<p style="text-transform: uppercase">
    {{value}}
</p>

ckanext/onboarding_baglan_adaskhan/templates/snippets/package_item.html
{% ckan_extends %}

{% block heading_title %}
    {{ super() }}
    {% set review_status = package.review_status %}

    {% set review_status_class = {
        "pending": "alert-warning",
        "approved": "alert-success",
        "rejected": "alert-danger"
    } %}
    {% snippet 'snippets/review_status_badge.html', review_status=review_status, review_status_class=review_status_class %}

{% endblock %}

ckanext/onboarding_baglan_adaskhan/templates/snippets/review_status_badge.html
<span class="dataset-private badge pull-right {{ review_status_class.get(review_status) }}"
      data-module="review-status-tooltip"
      data-module-review_status="{{ review_status }}">
  {{ _(review_status) }}
</span>

ckanext/onboarding_baglan_adaskhan/templates/user/snippets/info.html
{% ckan_extends %} 

{% block user_info %} 
    {{ super() }}
    <div class="info">
        <dl>
            <dt>{{ _('Has Review Permission?') }}</dt>
            <dd>{{ _('Yes') if h.user_is_reviewer(user.id) else _('No') }}</dd>
        </dl>
    </div>
{% endblock %}